<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>

<div style="position:absolute;top:0.64in;left:1.71in;width:5.90in;line-height:0.28in;"><DIV style="position:relative; left:1.39in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">PEMERINTAH </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:0.64in;left:1.71in;width:5.90in;line-height:0.28in;"><DIV style="position:relative; left:2.60in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">KABUPATEN </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:0.64in;left:1.71in;width:5.90in;line-height:0.28in;"><DIV style="position:relative; left:3.71in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">CIANJUR</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:0.90in;left:1.71in;width:5.90in;line-height:0.29in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Calibri-Bold;color:#000000">DINAS </span></SPAN><br/></div>
<div style="position:absolute;top:0.90in;left:1.71in;width:5.90in;line-height:0.29in;"><DIV style="position:relative; left:0.61in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Calibri-Bold;color:#000000">PERUMAHAN </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:0.90in;left:1.71in;width:5.90in;line-height:0.29in;"><DIV style="position:relative; left:1.84in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Calibri-Bold;color:#000000">KAWASAN </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:0.90in;left:1.71in;width:5.90in;line-height:0.29in;"><DIV style="position:relative; left:2.83in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Calibri-Bold;color:#000000">PERMUKIMAN </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:0.90in;left:1.71in;width:5.90in;line-height:0.29in;"><DIV style="position:relative; left:4.16in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Calibri-Bold;color:#000000">DAN </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:0.90in;left:1.71in;width:5.90in;line-height:0.29in;"><DIV style="position:relative; left:4.61in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Calibri-Bold;color:#000000">PERTANAHAN</span><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Calibri-Bold;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:0.57in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">Jalan </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:0.98in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">Adi </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:1.27in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">Sucipta </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:1.85in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">No. </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:2.15in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">7 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:2.28in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">Telepon </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:2.92in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">( </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:3.02in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">0263 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:3.43in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">) </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:3.53in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">261210 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:4.12in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">– </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.24in;"><DIV style="position:relative; left:4.25in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">Cianjur </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.16in;left:1.71in;width:5.90in;line-height:0.25in;"><DIV style="position:relative; left:4.82in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Calibri;color:#000000">43213</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:4.19in;left:2.86in;width:3.60in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">DOKUMEN </span></SPAN><br/></div>
<div style="position:absolute;top:4.19in;left:2.86in;width:3.60in;line-height:0.28in;"><DIV style="position:relative; left:0.99in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">SURAT </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.19in;left:2.86in;width:3.60in;line-height:0.28in;"><DIV style="position:relative; left:1.61in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">PERINTAH </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.19in;left:2.86in;width:3.60in;line-height:0.28in;"><DIV style="position:relative; left:2.53in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">KERJA </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.19in;left:2.86in;width:3.60in;line-height:0.28in;"><DIV style="position:relative; left:3.10in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">(SPK)</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:4.47in;left:2.86in;width:3.60in;line-height:0.28in;"><DIV style="position:relative; left:0.70in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">PENGADAAN </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.47in;left:2.86in;width:3.60in;line-height:0.28in;"><DIV style="position:relative; left:1.86in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">LANGSUNG</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.03in;left:1.79in;width:0.76in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">NOMOR</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.03in;left:2.81in;width:4.18in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">: </span></SPAN><br/></div>
<div style="position:absolute;top:5.03in;left:2.81in;width:4.18in;line-height:0.28in;"><DIV style="position:relative; left:0.23in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">602.4/SPK/PPK/ </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.03in;left:2.81in;width:4.18in;line-height:0.28in;"><DIV style="position:relative; left:1.65in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Perkimtan</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">–</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">ABS.</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">21</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">104</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">/2021</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.43in;left:1.79in;width:2.37in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">TANGGAL</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.43in;left:1.79in;width:2.37in;line-height:0.28in;"><DIV style="position:relative; left:1.02in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">: </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.43in;left:1.79in;width:2.37in;line-height:0.28in;"><DIV style="position:relative; left:1.25in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">11 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.43in;left:1.79in;width:2.37in;line-height:0.28in;"><DIV style="position:relative; left:1.51in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Mei </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.43in;left:1.79in;width:2.37in;line-height:0.28in;"><DIV style="position:relative; left:1.89in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">2021</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.51in;left:1.41in;width:1.06in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Nomor </span></SPAN><br/></div>
<div style="position:absolute;top:7.51in;left:1.41in;width:1.06in;line-height:0.28in;"><DIV style="position:relative; left:0.65in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">DPA</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.51in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.51in;left:3.80in;width:2.23in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">900/Kep.07/BPKAD/2021</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.91in;left:3.80in;width:1.19in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">08 </span></SPAN><br/></div>
<div style="position:absolute;top:7.91in;left:3.80in;width:1.19in;line-height:0.28in;"><DIV style="position:relative; left:0.26in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">April </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:7.91in;left:3.80in;width:1.19in;line-height:0.28in;"><DIV style="position:relative; left:0.72in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">2021</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.31in;left:1.41in;width:1.17in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Sub </span></SPAN><br/></div>
<div style="position:absolute;top:8.31in;left:1.41in;width:1.17in;line-height:0.28in;"><DIV style="position:relative; left:0.37in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kegiatan</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.31in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.31in;left:3.80in;width:3.75in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Pembangunan </span></SPAN><br/></div>
<div style="position:absolute;top:8.31in;left:3.80in;width:3.75in;line-height:0.28in;"><DIV style="position:relative; left:1.29in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">SPAM </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:8.31in;left:3.80in;width:3.75in;line-height:0.28in;"><DIV style="position:relative; left:1.85in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Jaringan </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:8.31in;left:3.80in;width:3.75in;line-height:0.28in;"><DIV style="position:relative; left:2.62in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Perpipaan </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:8.31in;left:3.80in;width:3.75in;line-height:0.28in;"><DIV style="position:relative; left:3.54in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">di</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.59in;left:3.80in;width:3.75in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kawasan </span></SPAN><br/></div>
<div style="position:absolute;top:8.59in;left:3.80in;width:3.75in;line-height:0.28in;"><DIV style="position:relative; left:0.81in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Perdesaan</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.99in;left:1.41in;width:0.90in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Pekerjaan</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.99in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.99in;left:3.80in;width:4.03in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Belanja </span></SPAN><br/></div>
<div style="position:absolute;top:8.99in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:0.68in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Barang/Jasa </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:8.99in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:1.77in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">yang </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:8.99in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:2.23in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">diserahkan </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:8.99in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:3.22in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">kepada</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:9.27in;left:3.80in;width:4.03in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">masyarakat </span></SPAN><br/></div>
<div style="position:absolute;top:9.27in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:1.04in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">(</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Pembuatan </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.27in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:2.15in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Sumur </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.27in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:2.76in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Bor </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.27in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:3.11in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kp. </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.27in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:3.43in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kebon</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:9.55in;left:3.80in;width:4.03in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kalapa </span></SPAN><br/></div>
<div style="position:absolute;top:9.55in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:0.62in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">RT </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.55in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:0.89in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">01/02 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.55in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:1.45in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Desa </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.55in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:1.92in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Mulyasari </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.55in;left:3.80in;width:4.03in;line-height:0.28in;"><DIV style="position:relative; left:2.81in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kec.Mande</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">)</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:9.95in;left:1.41in;width:0.58in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Lokasi</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.95in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.95in;left:3.80in;width:1.08in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kab. </span></SPAN><br/></div>
<div style="position:absolute;top:9.95in;left:3.80in;width:1.08in;line-height:0.28in;"><DIV style="position:relative; left:0.42in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Cianjur</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.35in;left:1.41in;width:1.46in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Tahun </span></SPAN><br/></div>
<div style="position:absolute;top:10.35in;left:1.41in;width:1.46in;line-height:0.28in;"><DIV style="position:relative; left:0.59in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Anggaran</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.35in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.35in;left:3.80in;width:0.48in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">2021</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.75in;left:1.41in;width:1.28in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Harga </span></SPAN><br/></div>
<div style="position:absolute;top:10.75in;left:1.41in;width:1.28in;line-height:0.28in;"><DIV style="position:relative; left:0.56in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kontrak</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.75in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.75in;left:3.80in;width:1.56in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Rp</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">.96</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">500</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">.000,00</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.15in;left:1.41in;width:1.74in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Waktu </span></SPAN><br/></div>
<div style="position:absolute;top:11.15in;left:1.41in;width:1.74in;line-height:0.28in;"><DIV style="position:relative; left:0.62in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Pelaksanaan</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:11.15in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.15in;left:3.80in;width:3.26in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">90 </span></SPAN><br/></div>
<div style="position:absolute;top:11.15in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:0.26in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">(Empat </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.15in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:0.93in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Puluh </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.15in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:1.47in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Lima) </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.15in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:1.99in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Hari </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.15in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:2.40in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Kalender </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.15in;left:3.80in;width:3.26in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.43in;left:3.80in;width:3.26in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">11 </span></SPAN><br/></div>
<div style="position:absolute;top:11.43in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:0.26in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Mei </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.43in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:0.65in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">2021 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.43in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:1.12in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">s/d </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.43in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:1.45in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">9 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.43in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:1.60in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Agustus </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.43in;left:3.80in;width:3.26in;line-height:0.28in;"><DIV style="position:relative; left:2.34in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">2021</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:11.83in;left:1.41in;width:0.84in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Penyedia</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.83in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.83in;left:3.80in;width:1.62in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">CV. </span></SPAN><br/></div>
<div style="position:absolute;top:11.83in;left:3.80in;width:1.62in;line-height:0.28in;"><DIV style="position:relative; left:0.33in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">BANGKIT </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.83in;left:3.80in;width:1.62in;line-height:0.28in;"><DIV style="position:relative; left:1.16in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">JAYA</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:12.23in;left:1.41in;width:0.66in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Alamat</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.23in;left:3.30in;width:0.10in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.23in;left:3.80in;width:0.66in;line-height:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Cianjur</span><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:6.02in;left:0.92in;width:2.91in;height:1.31in" src="ri_2.png" />
<img style="position:absolute;top:6.09in;left:1.04in;width:2.77in;height:1.16in" src="ci_3.png" />
<img style="position:absolute;top:6.09in;left:1.03in;width:2.78in;height:1.18in" src="ci_4.png" />
<img style="position:absolute;top:6.21in;left:1.10in;width:2.60in;height:0.98in" src="ri_3.png" />
<div style="position:absolute;top:6.53in;left:2.23in;width:0.38in;line-height:0.23in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Calibri-Bold;color:#000000">2021</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Calibri-Bold;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:13.09in;left:3.52in;width:2.63in;line-height:0.46in;"><span style="font-style:normal;font-weight:bold;font-size:22pt;font-family:Calibri-Bold;color:#000000">CV. </span></SPAN><br/></div>
<div style="position:absolute;top:13.09in;left:3.52in;width:2.63in;line-height:0.46in;"><DIV style="position:relative; left:0.54in;"><span style="font-style:normal;font-weight:bold;font-size:22pt;font-family:Calibri-Bold;color:#000000">BANGKIT </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:13.09in;left:3.52in;width:2.63in;line-height:0.46in;"><DIV style="position:relative; left:1.87in;"><span style="font-style:normal;font-weight:bold;font-size:22pt;font-family:Calibri-Bold;color:#000000">JAYA</span><span style="font-style:normal;font-weight:bold;font-size:22pt;font-family:Calibri-Bold;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:13.54in;left:4.50in;width:0.65in;line-height:0.23in;"><span style="font-style:normal;font-weight:normal;font-size:14pt;font-family:Calibri;color:#000000">Cianjur</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Helvetica;color:#333333"> </span><br/></SPAN></div>
<img style="position:absolute;top:1.48in;left:2.79in;width:3.49in;height:2.48in" src="ri_4.png" />
</body>
</html>
